import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  // Recording...
  await page.goto('https://demo.awecountant.com/');
await page.getByRole('textbox', { name: 'Email', exact: true }).fill('pramod@awecode.com');
await page.getByRole('textbox', { name: 'Password' }).click();
await page.getByRole('textbox', { name: 'Password' }).fill('admin');
await expect(page.getByRole('textbox', { name: 'Email', exact: true })).toBeVisible();
await expect(page.getByRole('textbox', { name: 'Password' })).toBeVisible();
await expect(page.getByRole('button', { name: 'Login' })).toBeVisible();
await page.getByRole('button', { name: 'Login' }).click();
await page.getByRole('button', { name: 'Expand "Banks & Wallets"' }).click();
await page.getByRole('listitem').filter({ hasText: 'Bank Accounts' }).click();
await expect(page.locator('div').filter({ hasText: /^New Accountadd$/ })).toBeVisible();
await page.getByRole('link', { name: 'New Account' }).click();
await expect(page.getByText('New AccountBank Account, e.g')).toBeVisible();
await page.getByRole('textbox', { name: 'Account Name' }).click();
await page.getByRole('textbox', { name: 'Account Name' }).fill('premium');
await page.getByRole('textbox', { name: 'Account Number *' }).click();
await page.getByRole('textbox', { name: 'Account Number *' }).fill('08957573888567');
await expect(page.getByRole('textbox', { name: 'Account Number *' })).toBeVisible();
await page.getByRole('textbox', { name: 'Bank Name' }).click();
await page.getByRole('textbox', { name: 'Bank Name' }).press('CapsLock');
await page.getByRole('textbox', { name: 'Bank Name' }).fill('C');
await page.getByRole('textbox', { name: 'Bank Name' }).press('CapsLock');
await page.getByRole('textbox', { name: 'Bank Name' }).fill('Citizen');
await page.getByRole('textbox', { name: 'Short Name' }).click();
await page.getByRole('textbox', { name: 'Short Name' }).fill('ctz');
await page.getByRole('textbox', { name: 'Bank Branch' }).click();
await page.getByRole('textbox', { name: 'Bank Branch' }).fill('biratnagar');
await page.getByRole('textbox', { name: 'Next Cheque No *' }).click();
await page.getByRole('textbox', { name: 'Next Cheque No *' }).fill('34578668');
await expect(page.getByRole('button', { name: 'Create' })).toBeVisible();
await page.getByRole('button', { name: 'Create' }).click();
await expect(page.getByRole('cell', { name: 'premium' })).toBeVisible();
await page.getByRole('listitem').filter({ hasText: 'Cheque Issues' }).click();
await page.getByRole('link', { name: 'New Cheque Issue' }).click();
await page.getByRole('combobox', { name: 'Bank Account *' }).fill('');
await page.getByRole('option', { name: 'ctz' }).locator('div').nth(1).click();
await page.getByRole('spinbutton', { name: 'Amount *' }).click();
await page.getByRole('spinbutton', { name: 'Amount *' }).fill('5677');
await page.locator('.col-8 > div > .q-field > .q-field__inner > .q-field__control > .q-field__control-container > .q-field__native').click();
await page.getByRole('option', { name: 'Quest College' }).locator('div').nth(2).click();
await expect(page.getByText('New Cheque IssuectzBank')).toBeVisible();
await page.getByRole('button', { name: 'Create' }).click();
await page.getByRole('listitem').filter({ hasText: 'Cheque Deposits' }).click();
await expect(page.locator('.q-table__top')).toBeVisible();
await expect(page.getByRole('row', { name: 'Quest College (Receivable) Issued 2025-01-31 View' }).getByRole('link')).toBeVisible();
await page.getByRole('row', { name: 'Quest College (Receivable) Issued 2025-01-31 View' }).getByRole('link').click();
await expect(page.getByText('Cheque Deposit | Issued | #1532Bank Account-BenefactorQuest College (Receivable')).toBeVisible();
await expect(page.getByRole('button', { name: 'Mark as cleared' })).toBeVisible();
await page.getByText('menuHome/Cheque Deposits/ViewFY 81-82 AD Dashboard Itemskeyboard_arrow_down All').click();
await page.getByRole('button', { name: 'Mark as cleared' }).click();
await page.getByRole('button', { name: 'Cancel' }).click();
await page.getByRole('button', { name: 'Yes' }).click();
await page.getByRole('button', { name: 'Expand "Reports"' }).click();
await page.getByRole('button', { name: 'Collapse "Reports"' }).click();
await page.getByRole('listitem').filter({ hasText: 'Cheque Deposits' }).click();
await page.getByRole('listitem').filter({ hasText: 'Cash Deposits' }).click();
await expect(page.getByText('New Cash Depositaddsearch')).toBeVisible();
await page.getByRole('link', { name: 'New Cash Deposit' }).click();
await page.locator('label').filter({ hasText: 'Bank Account *arrow_drop_down' }).locator('i').click();
await page.getByRole('option', { name: 'ctz' }).locator('div').nth(2).click();
await page.getByRole('combobox', { name: 'Benefactor *' }).click();
await page.getByRole('option', { name: '!"£$ (32434)' }).locator('div').nth(1).click();
await page.getByRole('spinbutton', { name: 'Amount *' }).click();
await page.getByRole('spinbutton', { name: 'Amount *' }).fill('5689');
await page.getByRole('spinbutton', { name: 'Voucher Number' }).click();
await page.getByRole('spinbutton', { name: 'Voucher Number' }).fill('657787');
await page.getByRole('textbox', { name: 'Deposited By' }).click();
await page.getByRole('textbox', { name: 'Deposited By' }).fill('abc');
await page.getByRole('textbox', { name: 'Narration' }).click();
await page.getByRole('textbox', { name: 'Narration' }).fill('for testing');
await expect(page.getByRole('button', { name: 'Create' })).toBeVisible();
await page.getByRole('button', { name: 'Create' }).click();
await page.getByRole('listitem').filter({ hasText: 'Funds Transfers' }).click();
await expect(page.getByText('New Fund Transferaddsearch')).toBeVisible();
await page.getByRole('link', { name: 'New Fund Transfer' }).click();
await page.getByRole('textbox', { name: 'Voucher No.' }).fill('9000909');
await page.getByRole('combobox', { name: 'From Account *' }).click();
await page.getByRole('option', { name: 'PB (74375745747557574)' }).locator('div').nth(1).click();
await page.getByRole('combobox', { name: 'To Account *' }).click();
await page.getByText('delectus').click();
await page.getByRole('textbox', { name: 'Amount *' }).click();
await page.getByRole('textbox', { name: 'Amount *' }).fill('6785');
await page.getByRole('combobox', { name: 'Fees Account' }).click();
await page.getByRole('option', { name: 'Nimb Commission', exact: true }).locator('div').nth(1).click();
await page.getByRole('spinbutton', { name: 'Fees Amount' }).click();
await page.getByRole('spinbutton', { name: 'Fees Amount' }).fill('98000');
await expect(page.getByText('New Fund TransferVoucher No.')).toBeVisible();
await page.getByRole('button', { name: 'Create' }).click();
await page.locator('td:nth-child(7)').first().click();
});