import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://demo.awecountant.com/');
  await page.getByRole('textbox', { name: 'Email', exact: true }).fill('pramod@awecode.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Expand "Items"' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Brands' }).click();
  await page.getByRole('link', { name: 'New brand' }).click();
  await page.getByRole('textbox', { name: 'Name *' }).fill('bikaji');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Description' }).fill('I');
  await page.getByRole('textbox', { name: 'Description' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Description' }).fill('Its bhujiya brand');
  await page.getByRole('button', { name: 'Create' }).click();
  
  await expect(page.locator('tbody')).toContainText('Its bhujiya brand');
  await page.getByText('inventoryInventory Ledger').click();
  await page.getByPlaceholder('Search').click();
  await page.getByPlaceholder('Search').fill('a');
  await page.goto('https://demo.awecountant.com/inventory-account/list/?search=a');
  await page.getByPlaceholder('Search').fill('app');
  await page.goto('https://demo.awecountant.com/inventory-account/list/?search=app');
  await page.getByPlaceholder('Search').fill('appli');
  await page.goto('https://demo.awecountant.com/inventory-account/list/?search=appli');
  await page.getByPlaceholder('Search').fill('applia');
  await page.goto('https://demo.awecountant.com/inventory-account/list/?search=applia');
  await page.getByPlaceholder('Search').fill('appliances');
  await page.goto('https://demo.awecountant.com/inventory-account/list/?search=appliances');
  await page.getByPlaceholder('Search').fill('appliance');
  await page.goto('https://demo.awecountant.com/inventory-account/list/?search=appliance');
  await expect(page.locator('tbody')).toContainText('appliance');
  await page.getByRole('link', { name: 'view' }).click();
  await page.getByRole('textbox', { name: 'Start Date' }).click();
  await page.getByText('Today').click();
  await page.getByRole('button', { name: 'FILTER' }).click();
  await page.getByRole('button', { name: 'FILTER' }).click();
  await page.getByRole('button', { name: 'FILTER' }).click();
  await page.getByText('inventoryInventory Ledger').click();
  await page.getByText('edit_noteOpening Stock').click();
  await page.getByRole('row', { name: 'electrical 50 EDIT' }).getByRole('link').nth(1).click();
  await page.locator('.q-field__inner').first().click();
  await page.getByRole('spinbutton', { name: 'Quantity *' }).click();
  await page.getByRole('spinbutton', { name: 'Quantity *' }).fill('70');
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByText('search').click();
  await page.getByPlaceholder('Search').click();
  await page.getByPlaceholder('Search').press('CapsLock');
  await page.getByPlaceholder('Search').press('CapsLock');
  await page.getByPlaceholder('Search').fill('choc');
  await page.goto('https://demo.awecountant.com/items/opening/?search=choc');
  await page.getByPlaceholder('Search').fill('choco');
  await page.goto('https://demo.awecountant.com/items/opening/?search=choco');
  await page.getByPlaceholder('Search').fill('chocolate');
  await page.goto('https://demo.awecountant.com/items/opening/?search=chocolate');
  await page.getByText('search').click();
  await expect(page.getByRole('cell', { name: 'chocolate' })).toBeVisible();
  await page.getByText('menuHome/Items/Stock OpeningFY 81-82 AD Dashboard Itemskeyboard_arrow_down All').click();
  await page.getByRole('listitem').filter({ hasText: 'Inventory Adjustment' }).click();
  await expect(page.getByRole('row', { name: '13 2025-01-30 Issued Stock In' }).locator('div').nth(1)).toBeVisible();
  await page.getByRole('row', { name: '13 2025-01-30 Issued Stock In' }).getByRole('link').nth(2).click();
  await page.getByRole('button', { name: 'Update' }).click();
});