import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://demo.awecountant.com/');
  await page.getByRole('textbox', { name: 'Email', exact: true }).fill('pramod@awecode.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin');
  await page.locator('label').filter({ hasText: 'Password' }).locator('i').nth(1).click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Expand "Items"' }).click();
  await page.getByRole('listitem').filter({ hasText: 'All Items' }).click();
  await expect(page.getByRole('row', { name: '{{nrandomame}} test99282892' }).getByRole('link').nth(2)).toBeVisible();
  await page.getByRole('link', { name: 'Add Item' }).click();
  await page.getByRole('textbox', { name: 'Name *' }).click();
  await page.getByRole('textbox', { name: 'Name *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Name *' }).fill('B');
  await page.getByRole('textbox', { name: 'Name *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Name *' }).fill('Billgates');
  await page.getByRole('textbox', { name: 'Code' }).click();
  await page.getByRole('textbox', { name: 'Code' }).fill('9667');
  await page.getByRole('spinbutton', { name: 'Cost Price' }).click();
  await page.getByRole('spinbutton', { name: 'Cost Price' }).fill('6000000');
  await page.getByRole('spinbutton', { name: 'Selling Price' }).click();
  await page.getByRole('spinbutton', { name: 'Selling Price' }).fill('65760000');
  await page.getByRole('combobox', { name: 'Brand' }).click();
  await page.getByRole('combobox', { name: 'Brand' }).fill('mercedes');
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Description' }).fill('I');
  await page.getByRole('textbox', { name: 'Description' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Description' }).fill('Its a car company');
  await page.locator('label').filter({ hasText: 'Categoryarrow_drop_down' }).locator('i').click();
  await page.getByRole('option', { name: 'Category1' }).locator('div').nth(1).click();
  await expect(page.getByRole('combobox', { name: 'Brand' })).toBeEmpty();
  await expect(page.getByRole('spinbutton', { name: 'Cost Price' })).toBeVisible();
  await expect(page.getByRole('textbox', { name: 'Code' })).toHaveValue('9667');
  await page.getByRole('button', { name: 'Create' }).click();
  await expect(page.getByRole('row', { name: 'Billgates Category1 6000000' }).getByRole('link').nth(3)).toBeVisible();
  await page.getByRole('row', { name: 'Billgates Category1 6000000' }).getByRole('link').nth(2).click();
  await expect(page.getByText('Inventory is Tracked')).toBeVisible();
  await expect(page.getByText('Can be Purchased')).toBeVisible();
  await expect(page.getByText('Can be Sold')).toBeVisible();
});