import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://demo.awecountant.com/login');
  await page.getByRole('textbox', { name: 'Email' }).fill('pramod@awecode.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin');
  await page.locator('.q-field__append').click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Expand "Accounts"' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Ledger' }).click();
  await page.getByPlaceholder('Search').click();
  await page.getByPlaceholder('Search').press('CapsLock');
  await page.getByPlaceholder('Search').fill('B');
  await page.getByPlaceholder('Search').press('CapsLock');
  await page.getByPlaceholder('Search').fill('Bank');
  await page.goto('https://demo.awecountant.com/account/?search=Bank&has_balance=true');
  await page.getByPlaceholder('Search').press('CapsLock');
  await page.getByPlaceholder('Search').fill('BankA');
  await page.getByPlaceholder('Search').press('CapsLock');
  await page.getByPlaceholder('Search').fill('BankAc');
  await page.goto('https://demo.awecountant.com/account/?search=BankAc&has_balance=true');
  await page.getByPlaceholder('Search').fill('BankAcc');
  await page.goto('https://demo.awecountant.com/account/?search=BankAcc&has_balance=true');
  await page.getByPlaceholder('Search').fill('BankAccounts');
  await page.goto('https://demo.awecountant.com/account/?search=BankAccounts&has_balance=true');
  await page.getByPlaceholder('Search').fill('');
  await page.goto('https://demo.awecountant.com/account/?has_balance=true');
  await page.getByPlaceholder('Search').press('CapsLock');
  await page.getByPlaceholder('Search').fill('B');
  await page.goto('https://demo.awecountant.com/account/?search=B&has_balance=true');
  await page.getByPlaceholder('Search').press('CapsLock');
  await page.getByPlaceholder('Search').fill('Bank');
  await page.goto('https://demo.awecountant.com/account/?search=Bank&has_balance=true');
  await page.getByPlaceholder('Search').fill('Bank ');
  await page.goto('https://demo.awecountant.com/account/?search=Bank+&has_balance=true');
  await page.getByPlaceholder('Search').press('CapsLock');
  await page.getByPlaceholder('Search').fill('Bank A');
  await page.goto('https://demo.awecountant.com/account/?search=Bank+A&has_balance=true');
  await page.getByPlaceholder('Search').press('CapsLock');
  await page.getByPlaceholder('Search').fill('Bank Acco');
  await page.goto('https://demo.awecountant.com/account/?search=Bank+Acco&has_balance=true');
  await page.getByPlaceholder('Search').fill('Bank Account');
  await page.goto('https://demo.awecountant.com/account/?search=Bank+Account&has_balance=true');
  await page.getByPlaceholder('Search').fill('Prabhu bank');
  await page.goto('https://demo.awecountant.com/account/?search=Prabhu+Bank&has_balance=true');
  await page.getByPlaceholder('Search').press('Enter');
  await page.getByRole('link', { name: 'New Account' }).click();
  await page.getByRole('textbox', { name: 'Name *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Name *' }).fill('C');
  await page.getByRole('textbox', { name: 'Name *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Name *' }).fill('Citizen bank');
  await page.getByRole('textbox', { name: 'Code' }).click();
  await page.getByRole('textbox', { name: 'Code' }).fill('09899');
  await page.locator('label').filter({ hasText: 'Parentarrow_drop_down' }).locator('i').click();
  await page.getByRole('option', { name: '51 Commission' }).locator('div').nth(2).click();
  await page.locator('label').filter({ hasText: 'Category *arrow_drop_down' }).locator('i').click();
  await page.getByRole('option', { name: 'Assets', exact: true }).locator('div').nth(1).click();
  await page.locator('label').filter({ hasText: 'Sourcearrow_drop_down' }).locator('i').click();
  await page.getByRole('option', { name: 'Audit Fee Payable' }).locator('div').nth(1).click();
  await page.getByRole('button', { name: 'Create' }).click();
  await expect(page.getByRole('row', { name: 'A-B-319 !"£$ (32434) Bank' }).getByRole('link').nth(3)).toBeVisible();
  await page.getByRole('row', { name: 'A-B-319 !"£$ (32434) Bank' }).getByRole('link').nth(3).click();
  await page.locator('label').filter({ hasText: 'Parentarrow_drop_down' }).locator('i').click();
  await page.getByText('5o Commission').click();
  await page.getByRole('combobox', { name: 'Source' }).click();
  await page.getByRole('option', { name: 'Audit Fee Payable' }).locator('div').nth(1).click();
  await page.getByRole('button', { name: 'Update' }).click();
});