import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://demo.awecountant.com/');
  await page.getByRole('textbox', { name: 'Email', exact: true }).fill('pramod@awecode.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin');
  await page.locator('label').filter({ hasText: 'Password' }).locator('i').nth(1).click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByText('Sales Amount by Party for last 7 DayseditSales Amount by Party for last 7').click();
  await page.getByRole('button', { name: 'Expand "Settings"' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Audit Logs' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Import/Exports' }).click();
  await expect(page.getByText('ExportPlease enter your password Password downloaddownloadImport Proceed with')).toBeVisible();
  await expect(page.getByText('ExportPlease enter your password Password downloaddownloadImport Proceed with')).toBeVisible();
  await page.getByText('ExportPlease enter your password Password downloaddownloadImport Proceed with').click();
  await page.getByRole('listitem').filter({ hasText: 'Dashboard Widgets' }).click();
  await expect(page.getByText('New Dashboard widgetaddNameDisplay TypeSales Amount by Party for last 7')).toBeVisible();
  await expect(page.getByRole('link', { name: 'New Dashboard widget' })).toBeVisible();
  await page.getByRole('link', { name: 'New Dashboard widget' }).click();
  await expect(page.locator('label').filter({ hasText: 'Widget Type *arrow_drop_down' }).locator('i')).toBeVisible();
  await page.locator('div').filter({ hasText: /^Widget Type \*$/ }).first().click();
  await page.getByRole('option', { name: 'Sales Amount by Party' }).locator('div').nth(1).click();
  await page.locator('label').filter({ hasText: 'Day(s)arrow_drop_down' }).locator('i').click();
  await page.getByText('Show data for lastDay(s)').click();
  await expect(page.getByText('menuHome/Dashboard Widgets/CreateFY 81-82 AD Dashboard Itemskeyboard_arrow_down')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Create' })).toBeVisible();
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Payment Modes' }).click();
  await expect(page.locator('div').filter({ hasText: 'New Payment' }).nth(3)).toBeVisible();
  await page.getByRole('link', { name: 'New Payment Mode' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('cheque');
  await page.locator('div').filter({ hasText: /^Account$/ }).first().click();
  await page.getByRole('option', { name: '51 Commission' }).locator('div').nth(1).click();
  await expect(page.getByText('CancelSave')).toBeVisible();
  await page.getByText('menuHome/Payment Mode/CreateFY 81-82 AD Dashboard Itemskeyboard_arrow_down All').click();
  await expect(page.getByRole('button', { name: 'Save' })).toBeVisible();
  await page.getByRole('button', { name: 'Save' }).click();
  await expect(page.getByRole('cell', { name: 'cheque' })).toBeVisible();
  await page.getByRole('listitem').filter({ hasText: 'Sales Settings' }).click();
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Purchase Settings' }).click();
  await expect(page.getByRole('button', { name: 'Update' })).toBeVisible();
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Inventory Settings' }).click();
  await expect(page.locator('form')).toBeVisible();
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Account Closing' }).click();
  await page.getByText('arrow_drop_down').click();
  await page.getByRole('option', { name: '/80' }).click();
  await page.getByRole('button', { name: 'Close Accounts' }).click();
  await expect(page.getByText('Your accounts for this year')).toBeVisible();
  await page.getByText('arrow_drop_down').click();
  await page.getByRole('option', { name: 'FY 81-' }).locator('div').nth(2).click();
  await page.getByText('menuHome/Account ClosingFY 81-82 AD Dashboard Itemskeyboard_arrow_down All').click();
  await page.getByRole('listitem').filter({ hasText: 'Item Merge' }).click();
  await page.getByText('arrow_drop_down').first().click();
  await page.getByRole('option', { name: 'Books (None)' }).click();
  await page.locator('label').filter({ hasText: 'Itemarrow_drop_down' }).locator('i').click();
  await page.getByRole('option', { name: 'Coco Beans (I - Cb)' }).click();
  await expect(page.getByText('Fetch Similar GroupsGroup')).toBeVisible();
  await page.getByRole('button', { name: 'Merge Items' }).click();
});