import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://demo.awecountant.com/');
  await page.getByRole('textbox', { name: 'Email', exact: true }).fill('pramod@awecode.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('admin');
  await page.locator('label').filter({ hasText: 'Password' }).locator('i').nth(1).click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Expand "Taxes"' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Tax Schemes' }).click();
  await expect(page.getByText('New Tax SchemeaddNamearrow_upwardShort')).toBeVisible();
  await expect(page.getByRole('link', { name: 'New Tax Scheme' })).toBeVisible();
  await page.getByRole('link', { name: 'New Tax Scheme' }).click();
  await page.getByRole('textbox', { name: 'Name *' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Name *' }).fill('NTC');
  await page.getByRole('textbox', { name: 'Name *' }).press('CapsLock');
  await expect(page.getByRole('textbox', { name: 'Name *' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Short Name' }).click();
  await page.getByRole('textbox', { name: 'Short Name' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Short Name' }).fill('N');
  await page.getByRole('textbox', { name: 'Short Name' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Short Name' }).fill('N');
  await page.getByRole('textbox', { name: 'Short Name' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Short Name' }).fill('NT');
  await page.getByRole('textbox', { name: 'Short Name' }).press('CapsLock');
  await page.getByRole('spinbutton', { name: 'Rate *' }).click();
  await page.getByRole('spinbutton', { name: 'Rate *' }).fill('567');
  await expect(page.getByRole('spinbutton', { name: 'Rate *' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Description' }).fill('I');
  await page.getByRole('textbox', { name: 'Description' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Description' }).fill('It is sim card');
  await expect(page.getByRole('textbox', { name: 'Description' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Create' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Create' })).toBeVisible();
  await page.getByRole('button', { name: 'Create' }).click();
  await page.getByRole('row', { name: 'NTC NT 567 Edit' }).getByRole('link').nth(1).click();
  await expect(page.getByRole('button', { name: 'Update' })).toBeVisible();
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Tax Payments' }).click();
  await expect(page.locator('.q-td > a').first()).toBeVisible();
  await expect(page.locator('.q-td > a').first()).toBeVisible();
  await page.locator('.q-td > a:nth-child(2)').first().click();
  await expect(page.getByText('Date : 2025-01-30AccountDR.CR')).toBeVisible();
  await page.getByRole('listitem').filter({ hasText: 'Periodic Summary' }).click();
  await page.getByRole('textbox', { name: 'Start Date' }).click();
  await expect(page.getByRole('textbox', { name: 'Start Date' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Start Date' }).click();
  await page.getByRole('textbox', { name: 'Start Date' }).click();

  await page.getByText('Last 30 Days').click();
  await page.getByRole('button', { name: 'fetch' }).click();
  await expect(page.locator('div').filter({ hasText: 'Start DateEnd DateclosefetchTransaction AmountTax on PurchaseTax on Sales1.' }).nth(3)).toBeVisible();
});